# fly.toml app configuration file generated for gweb2api on 2026-06-05T04:28:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gweb2api'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
